In [1]:
import numpy as np

In [23]:
def markov():
    init_array = np.array([1,0,0])
    E=np.array([13.5, 19.5, 25.5])
    transfer_mat = np.array([[0.625, 0.375, 0], 
                             [0.25, 0.58, 0.17], 
                             [0, 0.67, 0.33]])
    restmp = init_array
    for i in range(25): 
        res = np.dot(restmp, transfer_mat) 
        Ex= np.dot(res,E.T)
        print(f'N{i+1}\t{res} \n Ex \t {Ex}') 
        restmp = res
    # return restmp

In [21]:
E=np.array([13.5, 19.5, 25.5])

In [488]:
markov()

N1	[0.625 0.375 0.   ] 
 Ex 	 15.75
N2	[0.484375 0.451875 0.06375 ] 
 Ex 	 16.97625
N3	[0.41570313 0.48644062 0.09785625] 
 Ex 	 17.59291875
N4	[0.38142461 0.50358792 0.11498747] 
 Ex 	 17.90137715625
N5	[0.36428736 0.51215683 0.12355581] 
 Ex 	 18.055610700468748
N6	[0.35571881 0.51644111 0.12784008] 
 Ex 	 18.132727624516406
N7	[0.35143453 0.51858325 0.12998222] 
 Ex 	 18.17128609185807
N8	[0.3492924  0.51965432 0.13105328] 
 Ex 	 18.190565325715028
N9	[0.34822133 0.52018985 0.13158882] 
 Ex 	 18.20020494265002
N10	[0.34768579 0.52045762 0.13185659] 
 Ex 	 18.205024751117747
N11	[0.34741803 0.52059151 0.13199047] 
 Ex 	 18.207434655351616
N12	[0.34728414 0.52065845 0.13205741] 
 Ex 	 18.20863960746855
N13	[0.3472172  0.52069192 0.13209088] 
 Ex 	 18.20924208352702
N14	[0.34718373 0.52070865 0.13210762] 
 Ex 	 18.209543321556254
N15	[0.34716699 0.52071702 0.13211598] 
 Ex 	 18.209693940570872
N16	[0.34715863 0.5207212  0.13212017] 
 Ex 	 18.20976925007818
N17	[0.34715444 0.5207233  0.

In [22]:
np.dot(restmp,E.T)

18.209844412496604

In [48]:
import numpy as np
np.random.seed(0)
import math

In [426]:
# 定义状态转移概率矩阵P
P = np.array([
    [0.9, 0.1, 0.0, 0.0, 0.0, 0.0],
    [0.5, 0.0, 0.5, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.6, 0.0, 0.4],
    [0.0, 0.0, 0.0, 0.0, 0.3, 0.7],
    [0.0, 0.2, 0.3, 0.5, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]])

In [52]:
def compute_return(chain, gamma):
    k = len(chain)
    G = 0 
    for i in range(k):
        G += math.pow(gamma,i)*r_s[chain[i]-1]
    return G

In [427]:
r = np.array([-1,-2,-2,10,1,0]) #奖励函数
# 一个状态序列,s1-s2-s3-s6
chain = np.array([1,2,3,6])
# 一个状态序列,s1-s2-s3-s4-s6
# chain = np.array([1,2,3,4,6])
## 一个状态序列,s1-s2-s3-s4-s5-s3-s6
# chain = np.array([1,2,3,4,5,3,6])
gamma = 0.5 #折扣因子
G = compute_return(chain, gamma)
print("根据本序列计算得到回报为：%s。" % G)

根据本序列计算得到回报为：-2.5。


In [424]:
''' 利用贝尔曼方程的矩阵形式计算解析解'''
def compute_V(P,r,gamma):
    states_num = P.shape[0] # states_num是MRP的状态数
    rewards = r.reshape(-1,1) #奖励函数转换成列向量
    # V = r + gamma*P*V
    # V = inv(I-gamma*P) * r
    value = np.dot(np.linalg.inv(np.eye(states_num,states_num) - gamma*P),
                   rewards)
    return value

In [428]:
V = compute_V(P,r,gamma)
print("MRP中每个状态价值分别为\n", V)

MRP中每个状态价值分别为
 [[-2.01950168]
 [-2.21451846]
 [ 1.16142785]
 [10.53809283]
 [ 3.58728554]
 [ 0.        ]]


In [78]:
#利用贝尔曼方程进行验证，对状态s4,gamma = 0.5，有以下：
#V(s4) = r(s4) +gamma* sum(P(s'|s4)*V(s'))
# r(s4) = r_s[3] = 10
##sum(P(s'|s4)*V(s')) = P(s5|s4)*V(s5)+P(s6|s4)*V(s6) = 0.3*3.58728554+0.7*0 等价于 np.dot(P[3,:],V)
#V(s4) = 10+0.5*0.3*3.59=10.54 = V(s4)  

array([-1, -2, -2, 10,  1,  0])

In [475]:
S = ['s1','s2','s3','s4','s5'] #状态集合
A = ['保持s1','前往s2','前往s1','前往s3','前往s4','前往s5','概率前往']#动作集合
#状态转移函数
P0 ={
    's1-保持s1-s1':1,
    's1-前往s2-s2':1,
    's2-前往s1-s1':1,
    's2-前往s3-s3':1,
    's3-前往s4-s4': 1.0,
    's3-前往s5-s5': 1.0,
    's4-前往s5-s5': 1.0,
    's4-概率前往-s2':0.2,
    's4-概率前往-s3':0.4,
    's4-概率前往-s4':0.4
}
P_mat = np.array([
       [1, 1, 0., 0., 0.],
       [1, 0., 1, 0., 0.],
       [0., 0., 0., 1, 1],
       [0., 0.2, 0.4, 0.4, 1],
       [0., 0., 0., 0., 1]]) # s5终止状态（terminal state）,P(s5|s5) = 1 ，因为它不会再转移到其他状态，它永远以概率 1 转移到自己

#奖励函数
R0= {
    's1-保持s1':-1,
    's1-前往s2':0,
    's2-前往s1':-1,
    's2-前往s3':-2,
    's3-前往s4':-2,
    's3-前往s5':0,
    's4-前往s5':10,
    's4-概率前往':1
}
#R(s,a)= （5*7矩阵）
R_mat = np.array([[-1,0, 0, 0,  0, 0,0],
              [0 ,0,-1,-2,  0, 0,0],
              [0 ,0, 0, 0, -2, 0,0],
              [0 ,0, 0, 0,  0,10,1],
              [0 ,0, 0, 0,  0, 0,0]])
# R  = R_mat.sum(axis=1)
# #array([-1, -3, -2, 11,  0])
#折扣因子
gamma = 0.5
MDP = (S,A,P0,R0,gamma)
#策略1
Pi_1= {
    's1-保持s1':0.5,
    's1-前往s2':0.5,
    's2-前往s1':0.5,
    's2-前往s3':0.5,
    's3-前往s4':0.5,
    's3-前往s5':0.5,
    's4-前往s5':0.5,
    's4-概率前往':0.5 
}
π_mat_1 =  np.array([[0.5,0, 0, 0,  0, 0,0],
              [0 ,0,0.5,0.5,  0, 0,0],
              [0 ,0, 0, 0, 0.5, 0,0],
              [0 ,0, 0, 0,  0,0.5,0.5],
              [0 ,0, 0, 0,  0, 0,0]])

π_1 = np.array([
       [0.5, 0.5, 0., 0., 0.],
       [0.5, 0., 0.5, 0., 0.],
       [0., 0., 0., 0.5, 0.5],
       [0., 0.5, 0.5, 0.5, 0.5], 
       [0., 0., 0., 0., 1]])
#策略2
Pi_2= {
    's1-保持s1':0.6,
    's1-前往s2':0.4,
    's2-前往s1':0.3,
    's2-前往s3':0.7,
    's3-前往s4':0.5,
    's3-前往s5':0.5,
    's4-前往s5':0.1,
    's4-概率前往':0.9
}
π_mat_2 =  np.array([[0.6,0.4, 0, 0,  0, 0,0],
              [0 ,0,0.3,0.7,  0, 0,0],
              [0 ,0, 0, 0, 0.5, 0,0],
              [0 ,0, 0, 0,  0,0.1,0.9],
              [0 ,0, 0, 0,  0, 0,0]])
π_2 = np.array([
       [0.6, 0.4, 0., 0., 0.],
       [0.3, 0., 0.7, 0., 0.],
       [0., 0., 0., 0.5, 0.5],
       [0., 0.9, 0.9, 0.9, 0.1],
       [0., 0., 0., 0., 1]])
def join(str1,str2):
    return str1 + '-' + str2

In [477]:
def fit(π,π_mat,P,R,MDP,Pi):
    # 转化后的MRP的状态转移矩阵
    S,A,P0,R0,gamma =MDP
    P_prime = π*P
# array([[0.5, 0.5, 0. , 0. , 0. ],
#        [0.5, 0. , 0.5, 0. , 0. ],
#        [0. , 0. , 0. , 0.5, 0.5],
#        [0. , 0.1, 0.2, 0.2, 0.5],
#        [0. , 0. , 0. , 0. , 1. ]])
# 转化后的MRP的奖励函数
    R_prime = (π_mat*R_mat).sum(axis=1) 
# array([-0.5, -1.5, -1. ,  5.5,  0. ])
    V_π = compute_V(P_prime,R_prime,gamma)
    
    # print("MDP中每个状态价值分别为\n", V_π )
    V_π_dict = {}
    for i in range(len(S)):
        V_π_dict[S[i]] = float(V_π[i])
    print("MDP状态价值字典\n", V_π_dict )
    Q_π_dict = compute_Q(MDP,Pi,V_π_dict)
    print("MDP动作价值字典\n", Q_π_dict )
    # return V_π_dict

In [478]:
##使用策略1 Pi_1
print('使用策略一:')
fit(π_1,π_mat_1,P_mat,R_mat,MDP,Pi_1)
##使用策略1 Pi_2
print('使用策略二:')
fit(π_2,π_mat_2,P_mat,R_mat,MDP,Pi_2)

使用策略一:
MDP状态价值字典
 {'s1': -1.2255541069100393, 's2': -1.6766623207301177, 's3': 0.5189048239895697, 's4': 6.075619295958279, 's5': 0.0}
MDP动作价值字典
 {('s1', '保持s1'): -1.6127770534550196, ('s1', '前往s2'): -0.8383311603650588, ('s2', '前往s1'): -1.6127770534550196, ('s2', '前往s3'): -1.740547588005215, ('s3', '前往s4'): 1.0378096479791394, ('s3', '前往s5'): 0.0, ('s4', '前往s5'): 10.0, ('s4', '概率前往'): 2.1512385919165578}
使用策略二:
MDP状态价值字典
 {'s1': -1.4558505073116133, 's2': -2.0954767755906465, 's3': -0.5059977128397284, 's4': 1.976009148641086, 's5': 0.0}
MDP动作价值字典
 {('s1', '保持s1'): -1.7279252536558065, ('s1', '前往s2'): -1.0477383877953232, ('s2', '前往s1'): -1.7279252536558065, ('s2', '前往s3'): -2.252998856419864, ('s3', '前往s4'): -1.011995425679457, ('s3', '前往s5'): 0.0, ('s4', '前往s5'): 10.0, ('s4', '概率前往'): 1.0844546096012069}


/var/folders/6r/z2lzrvf17j52yzjsk2swb45w0000gn/T/ipykernel_41731/3202457662.py:17: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  V_π_dict[S[i]] = float(V_π[i])


In [466]:
def compute_Q(MDP,Pi_1,V_π_dict):
    S,A,P0,R0,gamma = MDP
    Q_π_dict ={}
    for key in Pi_1.keys():
        s,a=key.split('-')
        r = R0[key]
        temp,c = 0 ,0# rand是随机数，大于0 
        for s_opt in S:
            temp += P0.get(join(key,s_opt),0)#遍历查找，如果（s,a_opt,s_opt）在状态转移概率中找不到，返回0
            if temp > 0:# 筛选非None的（s,a_opt，s_opt）对，取值
                s_next = s_opt
                c += P0.get(join(key,s_opt),0)*V_π_dict[s_next]
        Q_π_dict[(s,a)] = r + gamma*c
    # print("计算MDP的动作价值为\n", Q_π_dict)
    return Q_π_dict
Q_π_dict = compute_Q(MDP,Pi_1,V_π_dict)

In [438]:
def sample(MDP,π,timestep_max,number):
    S,A,P,R,gamma = MDP
    episodes = []
    for num in range(number):
        episode= []
        timestep = 0
        s = S[np.random.randint(4)] # 随机选择一个除s5以外的状态s作为起点
        # np.random.shuffle(A)
        # 当前状态为终止状态或者时间步太长时,一次采样结束
        while s != 's5' and timestep <= timestep_max:
            timestep += 1
            rand, temp = np.random.rand(), 0 #rand是随机数，大于0 
             # 在状态s下根据策略选择动作
            for a_opt in A:
                temp += π.get(join(s,a_opt),0) #遍历查找，如果（s,a_opt）在动作策略中找不到，返回0
                if temp > rand: # 筛选非None的（s,a_opt）对，取值
                    a = a_opt
                    r = R.get(join(s,a))
                    break
            rand, temp = np.random.rand(), 0 #rand是随机数，大于0 
            # 根据状态转移概率得到下一个状态s_next
            for s_opt in S:
                temp += P.get(join(join(s,a_opt),s_opt),0)#遍历查找，如果（s,a_opt,s_opt）在状态转移概率中找不到，返回0
                if temp > rand:# 筛选非None的（s,a_opt，s_opt）对，取值
                    s_next = s_opt 
                    break
            episode.append((s,a,r,s_next))
            s = s_next
        # print(f'第{num+1}条序列\n', episode)
        episodes.append(episode)
        num += 1
    return episodes
# 采样5次,每个序列最长不超过20步
episodes = sample(MDP,Pi_1,20,5)

In [483]:
def MC(episodes,V,N,gamma):
    for episode in episodes:
        G = 0
        for i in range(len(episode)-1,-1,-1):#一个序列从后往前计算
            (s,a,r,s_next) = episode[i]
            G = r + gamma*G
            N[s] =  N[s] + 1
            V[s] =  V[s] + (G - V[s]) / N[s]
    print("使用蒙特卡洛方法计算MDP的状态价值为\n", V)
    return V
# 采样1000次,可以自行修改
episodes = sample(MDP, Pi_1, 20, 1000)
V,N = {'s1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0},{'s1': 0, 's2': 0, 's3': 0, 's4': 0, 's5': 0}
V = MC(episodes,V,N,gamma=0.5)

使用蒙特卡洛方法计算MDP的状态价值为
 {'s1': -1.2139343182008653, 's2': -1.6651032093089706, 's3': 0.5146363402066164, 's4': 6.246285732778469, 's5': 0}


In [486]:
Q = compute_Q(MDP,Pi_1,V)